### ISSUE TITLE
"flrom" command in .ini file doesn't work

### ISSUE THREAD

**Issue by fenugrec** [fenugrec/nisprog#1]
(reported by Shuher on IRC)

if the .ini file contains a flrom command, it will either crash (I wasn't able to confirm)
or automatically abort.

This is because cmd_flrom() prompts for some input using the same mechanism as the .ini command parser,

**Comment by fenugrec** [comment]
Possible fixes :
 - do not allow cmd_flrom() from an .ini file
 - make flrom non-interactive (yuck)
 - allow cmd_flrom() to interrupt the automated .ini file loading so it can ask its question normally

The last one will require a fix upstream to the freediag code ... not sure what will be needed there

**Comment by fenugrec** [comment]
ping @v-ladimir

**Comment by v-ladimir** [comment]
Option 1 would be more than enough, crashes are sucks, while having it run from .ini is definitely not life critical option🙂
