### ISSUE TITLE
Issues compiling on Linux

### ISSUE THREAD

**Issue by throwmeawayafterthat** [fenugrec/nisprog#23]
Hey, 
I got some issues compiling nisprog on my Laptop running openSuse TW and maybe you can give me some guidance.
I cloned nisprog via git, ran cmake and after that, make errors out with the following error:

`Consolidate compiler generated dependencies of target nisprog`
`[ 73%] Generating version.c, _version.c`
`[ 76%] Building C object CMakeFiles/nisprog.dir/version.c.o`
`[ 78%] Linking C executable nisprog`
`/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nisprog.dir/nissutils/cli_utils/nislib.c.o: in function 'find_eepread':`
`/home/max/nisprog/nissutils/cli_utils/nislib.c:641: undefined reference to 'sh_get_PCimm'`
`collect2: error: ld returned 1 exit status`
`make[2]: *** [CMakeFiles/nisprog.dir/build.make:235: nisprog] Error 1`
`make[1]: *** [CMakeFiles/Makefile2:139: CMakeFiles/nisprog.dir/all] Error 2`
`make: *** [Makefile:156: all] Error 2`

Any idea where I went wrong or what the issue might be?

**Comment by fenugrec** [comment]
git submodule init && git submodule update

looks like maybe your checkout of nissutils doesn't fit or is outdated. Should be @ 70277b296

**Comment by throwmeawayafterthat** [comment]
Yeah thank you, it worked now.  I didn't use the submodule commands but cloned freediag and nissutils manually at first cause the linked nissutils @ ... gave me a 404 yesterday for whatever reason.
