### ISSUE TITLE
2002 Nissan Maxima 

### ISSUE THREAD

**Issue by Phalp** [fenugrec/nisprog#5]
I was dumping my ECU 2002 nissan maxima, and as it got done and I opened it in romraider to check it out, I hit the USB cord and it came out. I didn't get to close the connection or even get the ECU functioning on its own. When. I tried to reconnect I got this

diag_os_gethrt() resolution <= 0us, avg ~0us
diag_os_getms() resolution: ~16ms.
diag_os_chronoms() : resolution: ~15ms
Calibrating timing, this will take a few seconds...
Calibration done.
nisprog v1.02
nisprog: Interface set to default: DUMB
nisprog: Type HELP for a list of commands
nisprog: Type SCAN to start ODBII Scan
nisprog: Then use MONITOR to monitor real-time data
nisprog: **** IMPORTANT : this is beta software ! Use at your own risk.
nisprog: **** Remember, "debug all -1" displays all debugging info.
interface is now DUMB
Note concerning generic (dumb) interfaces : there are additional
options which can be set with "set dumbopts". By default
"K-line only" and "MAN_BREAK" are set.
port set to: \\.\COM4
dumbopts set to:    72
testerid: using 0xFC
destaddr: using 0x10
diag_l2_iso14230.c:736: Read/Write timeout.
diag_l2.c:438: Read/Write timeout.
L2 StartComms failed
nisprog: Settings loaded from nisprog.ini

nisprog>

**Comment by Phalp** [comment]
Figured it out!

**Comment by Tyler11777** [comment]
I'm having the same issue any tips on how to resolve it would be much appreciated!

**Comment by mrphyslaw** [comment]
Remove power from the ECU. Typically the kernel is still running and won't connect. Be warned, DO NOT remove power if you have started a flash it may brick the ECU.Only remove power if you are dumping. If you have a failed flash head over to the Romraider forums and you can likely get help there.
